Add https://docs.micronaut.io/snapshot/guide/index.html#views[Server Side View Rendering] and https://www.thymeleaf.org/[Thymeleaf] dependencies:

[source, groovy]
.build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/build.gradle[tag=views]
}
----

Create a controller:

[source, java]
.src/main/java/example/micronaut/HomeController.java
----
include::{sourceDir}/src/main/java/example/micronaut/HomeController.java[]
----

<1> The class is defined as a controller with the `@Controller` annotation mapped to the path `/`
<2> Constructor injection
<3> Use `@View` annotation to specify which template would you like to render the response against.
<4> You can specify the HTTP verb for which a controller's action responds to. To respond to a GET request, use `io.micronaut.http.annotation.Get`
<5> `AttachedFile` is used as the return value of a route execution to indicate the given file should be downloaded by the client instead of displayed.

The previous controller index method renders a simple view with a link to download the excel file:

[source, html]
.src/main/resources/views/index.html
----
include::{sourceDir}/src/main/resources/views/index.html[]
----

